language: rust
rust:
  - stable
  - nightly

env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.6

before_script:
  - pyenv install -s $PYTHON_VERSION
  - pyenv local $PYTHON_VERSION
  - virtualenv ~/venv
  - . ~/venv/bin/activate

script:
  - make install-dev test

matrix:
  include:
    - rust: nightly
      env: PYTHON_VERSION=3.6
      script: make install-style style
  allow_failures:
    - script: make install-style style

cache:
  directories:
    - ~/.rustup/
    - ~/.cache/pip/
    - ~/.cargo/
